name: Build whole solution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lib:
    name: Build PassGen.Lib
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build project
      run: dotnet build PassGen.Lib
  global_tool:
    name: Build PassGen.GlobalTool
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build project
      run: dotnet build PassGen.GlobalTool
  tests:
    name: Build PassGen.Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build project
      run: dotnet build PassGen.Tests
  maui:
    name: Build PassGen.Maui
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Build project
      run: dotnet build PassGen.Maui
  web:
    name: Build PassGen.Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build project
      run: dotnet build PassGen.Web
