name: Build and upload nupkg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/SpinDOS/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore
    - name: Pack nupkg
      run: dotnet pack --configuration Release --no-restore --output ./out
    - name: Upload nupkg to GitHub
      run: dotnet nuget push "./out/*.nupkg" --skip-duplicate --no-symbols true
