name: Build Maui Android APK file

on: workflow_dispatch

jobs:
  build_and_upload:
    name: Build and upload APK
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install .NET MAUI
        run: dotnet workload install maui
      - name: Restore dependencies
        run: dotnet restore PassGen.Maui
      - name: Run dotnet publish
        working-directory: ./PassGen.Maui
        run: dotnet publish --no-restore --configuration Release --framework net8.0-android --output ./out
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.alexanderplat.passgen.maui-Signed.apk
          path: ./PassGen.Maui/out/com.alexanderplat.passgen.maui-Signed.apk
