name: Build Maui Android APK file

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_upload:
    name: Build and upload APK
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install .NET MAUI
        run: dotnet workload install maui
      - name: Restore dependencies
        run: dotnet restore PassGen.Maui
      - name: Unpack keystore for APK signing
        shell: pwsh
        env:
          PASSGEN_MAUI_KEYSTORE_BASE64: ${{ secrets.PASSGEN_MAUI_KEYSTORE_BASE64 }}
        working-directory: ./PassGen.Maui
        run: |
          echo "$env:PASSGEN_MAUI_KEYSTORE_BASE64" > passgen_maui_base64.txt
          python -c 'import base64, sys; base64.decode(open(sys.argv[1], "rb"), open(sys.argv[2], "wb"))' passgen_maui_base64.txt passgen_maui.keystore
      - name: Run dotnet publish
        env:
          PASSGEN_MAUI_KEYSTORE_PASSWORD: ${{ secrets.PASSGEN_MAUI_KEYSTORE_PASSWORD }}
        working-directory: ./PassGen.Maui
        run: dotnet publish --no-restore --configuration Release --framework net8.0-android --output ./out -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=passgen_maui.keystore -p:AndroidSigningKeyAlias=passgen_maui -p:AndroidSigningKeyPass=env:PASSGEN_MAUI_KEYSTORE_PASSWORD -p:AndroidSigningStorePass=env:PASSGEN_MAUI_KEYSTORE_PASSWORD
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.alexanderplat.passgen.maui-Signed.apk
          path: ./PassGen.Maui/out/com.alexanderplat.passgen.maui-Signed.apk
