name: Build and upload nupkg

on: workflow_dispatch

jobs:
  build_and_upload:
    name: Build and upload .nupkg
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "7.0"
        source-url: https://nuget.pkg.github.com/SpinDOS/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore PassGen.GlobalTool
    - name: Pack nupkg
      run: dotnet pack PassGen.GlobalTool --configuration Release --no-restore --output ./out
    - name: Upload nupkg to GitHub
      run: dotnet nuget push "./out/*.nupkg" --api-key ${NUGET_AUTH_TOKEN} --skip-duplicate --no-symbols
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: passgen.nupkg
        path: ./out/*.nupkg

